# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  schedule:
    - cron: "0 0 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    name: Generate a Markdown file from webpages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: node index.js
      - name: Generate build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: site

  build:
    name: Generate a PDF file
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v1
      - name: Install format conversion tools
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-linux-amd64.tar.gz -O /tmp/pandoc.tar.gz
          tar xfz /tmp/pandoc.tar.gz -C /tmp
          sudo mv /tmp/pandoc-*/bin/* /usr/bin
      - name: Recursively compile md files
        run: ./.github/workflows/rec "*\.md$" ${GITHUB_WORKSPACE}/.github/workflows/md2pdf
      - name: Generate build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: .

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Download static site artifact
        uses: actions/download-artifact@v2
        with:
          name: build-result
          path: site

      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: site
